document.writeln("<div style=\"background-color: #ededed; line-height: 1.5em; font-size: 1.1rem; padding: 16px 16px 16px 16px; margin: 8px 0px 8px 0px;\">");
document.write("如果您喜歡這篇文章，除了按讚、拍手，也歡迎分享到自己的社群中，文章採用<a href=\"https://creativecommons.org/licenses/by-nc-sa/3.0/tw/\" target=\"_blank\">創用 CC 姓名標示-非商業性-相同方式分享 3.0 台灣 授權條款</a>授權，");
document.write("分享、引用請依授權規定，並附上原文連結：");
//document.write("<a href=\""+location.href+"?utm_source=blogshare\" target=\"_blank\">");
//document.write("<a href=\""+location.protocol+"/"+location.hostname+location.pathname+"?utm_source=blogshare\" target=\"_blank\">");
document.write("<a href=\""+location.protocol+"//"+location.hostname+location.pathname+"?utm_source=blogshare\" target=\"_blank\">");
document.write(document.title);
document.write("</a>。");
document.writeln ('<br />聯絡我們');
document.writeln ('<a href="mailto:service@herearoma.com" style="margin: 1em; background-color:#dd4b39; color: #fff; border-radius:1em; padding: 0.3em; padding-left: 0.8em; padding-right: 0.8em; font-size: 0.9em;">Email</a>');
document.writeln ('<a href="https://he2.tw/fbpage" style="margin: 1em; background-color:#3b5998; color: #fff; border-radius:1em; padding: 0.3em; padding-left: 0.8em; padding-right: 0.8em; font-size: 0.9em;">FB 粉絲專頁</a>');
document.writeln ('<a href="https://he2.tw/lineat" style="margin: 1em; background-color:#00c300;; color: #fff; border-radius:1em; padding: 0.3em; padding-left: 0.8em; padding-right: 0.8em; font-size: 0.9em;">加入 LINE 好友</a>');
document.writeln("</div>");
